# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aebd81570a6309c9ee816e3b1351bda7bfc3c350f579db9fd366352c7af08710f6190c3b77b07e3ab98c4ca5eab3782a0527d5bd9879a157bdcaacb30a3d33eb

test:
  secret_key_base: 38f9fd207d2b417f93b9903df745e127e518ac1f6026468162f86c05094a6264d5dede2c3012360717c51cfd969dbe8a2589fa453a61224159868de2f62e8a31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
